name: Run NSE Entry Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/main_sell.yml"
      - "sell_breakdown_1000.py"

  workflow_dispatch:

  schedule:
    # 09:17 IST = 03:47 UTC
    - cron: "47 3 * * 1-5"

    # 03:34 PM IST = 10:04 UTC
    - cron: "4 10 * * 1-5"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ----------------------------
      # Live Entry Snapshot
      # ----------------------------
      - name: Run entry point script
        env:
          MONGO_URL: ${{ secrets.MONGO_URI }}
          TELEGRAM_DATA: ${{ secrets.TELEGRAM_DATA }}
        run: |
          python buy_breakout_915.py
